"""empty message

Revision ID: d79bf9c9f51a
Revises: 
Create Date: 2025-04-22 19:35:11.413195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79bf9c9f51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('target_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('dc_ip', sa.String(length=45), nullable=True),
    sa.Column('target_subnets', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name')
    )
    op.create_table('assessment_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('progress_task', sa.String(length=255), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('selected_modules', sa.Text(), nullable=True),
    sa.Column('users_count', sa.Integer(), nullable=True),
    sa.Column('groups_count', sa.Integer(), nullable=True),
    sa.Column('computers_count', sa.Integer(), nullable=True),
    sa.Column('critical_findings', sa.Integer(), nullable=True),
    sa.Column('high_findings', sa.Integer(), nullable=True),
    sa.Column('medium_findings', sa.Integer(), nullable=True),
    sa.Column('low_findings', sa.Integer(), nullable=True),
    sa.Column('info_findings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['target_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_computer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dns_hostname', sa.String(length=255), nullable=True),
    sa.Column('distinguished_name', sa.Text(), nullable=True),
    sa.Column('object_sid', sa.String(length=255), nullable=True),
    sa.Column('sam_account_name', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('distinguished_name', sa.Text(), nullable=True),
    sa.Column('object_sid', sa.String(length=255), nullable=True),
    sa.Column('sam_account_name', sa.String(length=255), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('sam_account_name', sa.String(length=255), nullable=True),
    sa.Column('user_principal_name', sa.String(length=255), nullable=True),
    sa.Column('distinguished_name', sa.Text(), nullable=True),
    sa.Column('object_sid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('affected_objects', sa.JSON(), nullable=True),
    sa.Column('remediation_steps', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('password_history', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('lockout_threshold', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.Boolean(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('strength_counts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_type', sa.String(length=50), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ad_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_computer',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('computer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['computer_id'], ['ad_computer.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'computer_id')
    )
    op.create_table('finding_group',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['ad_group.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'group_id')
    )
    op.create_table('finding_user',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ad_user.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_user')
    op.drop_table('finding_group')
    op.drop_table('finding_computer')
    op.drop_table('ad_group_membership')
    op.drop_table('password_policy')
    op.drop_table('finding')
    op.drop_table('ad_user')
    op.drop_table('ad_group')
    op.drop_table('ad_computer')
    op.drop_table('assessment_run')
    op.drop_table('target_config')
    op.drop_table('application_user')
    # ### end Alembic commands ###
