"""empty message

Revision ID: da63bf3c530d
Revises: 8433780f19cb
Create Date: 2025-04-26 14:27:29.084905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da63bf3c530d'
down_revision = '8433780f19cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwd_last_set', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_age_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('password_expired', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_logon_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('password_policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_password_stats', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_policy', schema=None) as batch_op:
        batch_op.drop_column('user_password_stats')

    with op.batch_alter_table('ad_user', schema=None) as batch_op:
        batch_op.drop_column('account_status')
        batch_op.drop_column('last_logon_timestamp')
        batch_op.drop_column('password_expired')
        batch_op.drop_column('password_age_days')
        batch_op.drop_column('pwd_last_set')

    # ### end Alembic commands ###
